let mobLibrary = [
  {
    entry: 'stone',
    title: 'Black Practice Stone',
    roomDesc: "You can practice attacking and honing your skills on the black <w>stone</w>.",
    inspectDesc: "This stone is wider than you are tall. It looks like some derivative of obsidian with its glass-like shimmer.",
    aggroDesc: false,
    deathDesc: "The stone cracks for a moment<span class='default'>, then pieces itself back together.</span>",
    atkVerb: "glares at",
    class: ['medium'],
    HPFactor: 5,
    dmgFactor: 0,
    atkSpd: 0,
    spreadFactor: 1,
    guardWait: 0,
    guardCounter: 0,
    hit: 0,
    evade: 0,
    aggro: false,
    aggroWait: 0,
    passive: true,
    living: true,
    unique: true,
    XPFactor: 0,
    loot1: false, //item category, tier, % chance, qty
    loot2: false,
    plasmoidFactor: 1,
    ID: 0,
    deathFunc: function(thisMobInstance) {
      thisMobInstance.currentHP = thisMobInstance.maxHP;
      thisMobInstance.HPRatio = 1;
      thisMobInstance.living = true;
    }
  },
  {
    entry: ['shadow', 'spawn'],
    title: 'Shadow Spawn',
    roomDesc: "A hapless Shadow <w>Spawn</w> warrior wanders here.",
    roomDescPlural: "Shadow Spawn warriors wander here.",
    roomDescDeath: "A slain Shadow Spawn lies slumped here.",
    inspectDesc: "The Shadow Spawn scampers about, metal boots clacking.",
    inspectDescDeath: "The Shadow Spawn's dark blood still oozes from its wounds.",
    aggroDesc: false,
    deathDesc: "The Shadow Spawn lets out a pained cry as it falls to the ground.",
    atkVerb: "punches",
    class: ['small'],
    HPFactor: 2,
    dmgFactor: 2,
    atkSpd: 12,
    spreadFactor: 1,
    guardWait: 0,
    guardCounter: 0,
    hit: 0.85,
    evade: 0,
    aggro: false,
    aggroWait: 0,
    living: true,
    XPFactor: 0,
    plasmoidFactor: .1,
    loot1: ['monster', 1, .6], //item category, tier, % chance, qty
    loot2: false,
    ID: 1
  },
  {
    entry: ['dark', 'one'],
    title: 'Dark One',
    roomDesc: "A Dark <w>One</w> patrols here.",
    roomDescDeath: "The corpse of a Dark One lies here.",
    inspectDesc: "A hulking warrior and cornerstone of the Dark Army.",
    inspectDescDeath: "Its black armor is sprinkled with blood.",
    aggroDesc: "The Dark One yells furiously, ready to attack!",
    deathDesc: "The Dark One lets out a blood-curdled groan and slumps over lifelessly.",
    atkVerb: "strikes",
    class: ['medium'],
    HPFactor: 4,
    dmgFactor: 4,
    atkSpd: 11,
    spreadFactor: 2,
    guard: false, //this is set to TRUE after milestone 1
    guardWait: 4,
    guardCounter: 0,
    hit: 0.7,
    evade: 0,
    aggro: false, //if this enemy will automatically start attacking  //this is set to TRUE after milestone 1
    aggroWait: 5, //how many seconds it takes to start attacking
    living: true,
    unique: true,
    XPFactor: 0,
    plasmoidFactor: .2,
    loot1: ['monster', 1, .6], //ID of item
    loot2: false,
    ID: 2
  },
  {
    entry: ['pest'],
    title: 'Pest',
    roomDesc: "A oversized <w>Pest</w> flutters its translucent wings.",
    roomDescDeath: "A Pest's bloodied pulp stains the ground.",
    inspectDesc: "Its many insect-like wings buzz with bulbous mutations.",
    inspectDescDeath: "Its mutations still thrum with life, feeding on the corpse.",
    aggroDesc: false,
    deathDesc: "Black dust scatters, and the Pest's wings become still.",
    atkVerb: "bites",
    class: ['small'],
    HPFactor: 1,
    dmgFactor: 1,
    atkSpd: 6,
    spreadFactor: 2,
    guardWait: 0,
    guardCounter: 0,
    hit: 0.7,
    evade: 0,
    aggro: false,
    aggroWait: 0,
    living: true,
    XPFactor: 0,
    plasmoidFactor: .1,
    loot1: ['mystical', 1, .6],
    loot2: false,
    ID: 3
  },
  {
    entry: 'raven',
    title: 'Raven',
    roomDesc: "A mutated <w>Raven</w> flies low overhead.",
    roomDescDeath: "A monstrous Raven lies dead.",
    inspectDesc: "An elusive and unpredictable foe. Pesters its prey with its numerous talons.",
    inspectDescDeath: "Its crumpled feathers still swarm with dark energy.",
    aggroDesc: false,
    deathDesc: "The Raven falls dead.",
    atkVerb: "claws",
    class: ['medium'],
    HPFactor: 3,
    dmgFactor: 5,
    atkSpd: 8,
    spreadFactor: 1,
    guardWait: 0,
    guardCounter: 0,
    hit: 0.9,
    evade: 0,
    aggro: false,
    aggroWait: 0,
    living: true,
    XPFactor: 0,
    plasmoidFactor: .15,
    loot1: ['mystical', 1, .3],
    loot2: false,
    ID: 4
  },
  {
    entry: ['walker', 'shadow'],
    title: 'Shadow Walker',
    roomDesc: "A Shadow <w>Walker</w> looms here.",
    roomDescDeath: "The severed limbs of a Shadow Walker are strewn about.",
    inspectDesc: "Its long, sword-like limbs dangle from its gaunt body.",
    inspectDescDeath: "Its shriveled skin is pulled tight over its lifeless bones.",
    aggroDesc: false,
    deathDesc: "The Shadow Walker lets out a pained cry as it topples over.",
    atkVerb: "punctures",
    class: ['medium'],
    HPFactor: 5,
    dmgFactor: 7,
    atkSpd: 13,
    spreadFactor: 3,
    guard: true,
    guardWait: 3,
    guardCounter: 0,
    hit: 0.5,
    evade: 0,
    aggro: true,
    aggroWait: 4,
    skills: [
      {
        entry: ['ripper'],
        title: 'Ripper',
        interruptable: true,
        startup: 36, //how many ticks it takes to execute
        freq: 3, //how often it will roll for this skill (in turns)
        freqChance: .4, //how often it will actually use the skill on that turn
        numOfAtks: 1,
        dmgFactor: 3,
        hit: .85,
        telegraph: "The Walker bends backwards and <sk>charges an attack</sk>!",
        hitLog: "The Walker lunges forwards with its long blades, <r>tearing into you</r>",
        missLog: "The Walker lunges with its finger-like blades, but <g>misses</g>!",
      }
    ],
    living: true,
    XPFactor: 0,
    plasmoidFactor: .3,
    loot1: ['mystical', 2, .65],
    loot2: ['monster', 1, .85],
    ID: 5
  },
  {
    entry: ['defender', 'dusk'],
    title: 'Dusk Defender',
    roomDesc: "A Dusk <w>Defender</w> stands guard.",
    roomDescDeath: "The bloody shield of a Dusk Defender lies here.",
    inspectDesc: "This hulking guard carries a huge shield, ready to push the front lines of the dark army.",
    inspectDescDeath: "Thick plate armor covers bloodied creature entrails.",
    aggroDesc: false,
    deathDesc: "The Dusk Defender falls to his knees, armor clattering.",
    atkVerb: "bashes",
    class: ['large'],
    HPFactor: 6,
    dmgFactor: 3.5,
    atkSpd: 12,
    spreadFactor: 1,
    guard: true,
    guardWait: 0,
    guardCounter: 0,
    hit: 0.80,
    evade: 0,
    aggro: false,
    aggroWait: 0,
    living: true,
    XPFactor: 0,
    plasmoidFactor: .35,
    loot1: ['science', 1, .4],
    loot2: ['monster', 1, .6],
    ID: 6
  },
  {
    entry: ['royal', 'templar'],
    title: 'Royal Templar',
    roomDesc: "A Royal <w>Templar</w> patrols here.",
    roomDescDeath: ".",
    inspectDesc: "Templars form the base of Ungola's legion. They are brutal and have never known defeat.",
    inspectDescDeath: ".",
    aggroDesc: false,
    deathDesc: "dies",
    atkVerb: "skewers",
    class: ['medium'],
    HPFactor: 7,
    dmgFactor: 8,
    atkSpd: 10,
    spreadFactor: 1,
    guard: true,
    guardWait: 4,
    guardCounter: 0,
    hit: 0.75,
    evade: 0,
    aggro: true,
    aggroWait: 0,
    living: true,
    XPFactor: 0,
    plasmoidFactor: .15,
    loot1: ['monster', 3, .6],
    loot2: ['science', 2, .2],
    ID: 7
  },
  {
    entry: ['abomination'],
    title: 'Abomination',
    roomDesc: "An <w>Abomination</w> of the dark army thunders by.",
    roomDescDeath: "",
    inspectDesc: "A grotesque mutant made from sacrifices and dark magic. Feeds on the stench of blood.",
    inspectDescDeath: "",
    aggroDesc: false,
    deathDesc: "dies",
    atkVerb: "thrashes",
    class: ['large'],
    HPFactor: 9,
    dmgFactor: 10,
    atkSpd: 10,
    spreadFactor: 1,
    guard: true,
    guardWait: 6,
    guardCounter: 0,
    hit: 0.45,
    evade: 0,
    aggro: true,
    aggroWait: 0,
    living: true,
    XPFactor: 0,
    plasmoidFactor: .15,
    loot1: ['monster', 3, .6],
    loot2: ['mystical', 1, .2],
    ID: 8
  },
  {
    entry: ['onyx', 'golem'],
    title: 'Onyx Golem',
    roomDesc: "A giant Onyx <w>Golem</w> stands watch.",
    roomDescDeath: "",
    inspectDesc: "Summoned by some strange incantations, these golems tear through nearly everything.",
    inspectDescDeath: "",
    aggroDesc: false,
    deathDesc: "dies",
    atkVerb: "decimates",
    class: ['large'],
    HPFactor: 10,
    dmgFactor: 10,
    atkSpd: 10,
    spreadFactor: 1,
    guard: true,
    guardWait: 3,
    guardCounter: 0,
    hit: 0.7,
    evade: 0,
    aggro: true,
    aggroWait: 0,
    living: true,
    XPFactor: 0,
    plasmoidFactor: .15,
    loot1: ['monster', 3, .6],
    loot2: false,
    ID: 9
  },
  {
    entry: ['royal', 'protector'],
    title: 'Royal Protector',
    roomDesc: "A Royal <w>Protector</w> holds the line of defense.",
    roomDescDeath: "",
    inspectDesc: "Protectors form stalwart defenses against Ungola's foes. Their scaly skin has fused with the armor they carry.",
    inspectDescDeath: "",
    aggroDesc: false,
    deathDesc: "dies",
    atkVerb: "",
    class: ['large'],
    HPFactor: 10,
    dmgFactor: 9,
    atkSpd: 10,
    spreadFactor: 1,
    guardWait: 0,
    guardCounter: 0,
    hit: 0.9,
    evade: 0,
    aggro: false,
    aggroWait: 0,
    living: true,
    XPFactor: 0,
    plasmoidFactor: .15,
    loot1: ['science', 3, .6],
    loot2: ['mystical', 3, .1],
    ID: 10
  },
  {
    entry: [''],
    title: 'Electric Petri',
    roomDesc: ".",
    roomDescDeath: ".",
    inspectDesc: ".",
    inspectDescDeath: ".",
    aggroDesc: false,
    deathDesc: "dies",
    atkVerb: "strikes",
    class: ['small'],
    HPFactor: 1,
    dmgFactor: 2,
    atkSpd: 10,
    spreadFactor: 1,
    guardWait: 0,
    guardCounter: 0,
    hit: 0.9,
    evade: 0,
    aggro: true,
    aggroWait: 0,
    living: true,
    XPFactor: 0,
    plasmoidFactor: .15,
    loot1: ['monster', 0, 0],
    loot2: false,
    ID: 0
  },
  {
    entry: [''],
    title: 'Miter',
    roomDesc: ".",
    roomDescDeath: ".",
    inspectDesc: ".",
    inspectDescDeath: ".",
    aggroDesc: false,
    deathDesc: "dies",
    atkVerb: "strikes",
    class: ['small'],
    HPFactor: 2,
    dmgFactor: 4,
    atkSpd: 10,
    spreadFactor: 1,
    guardWait: 0,
    guardCounter: 0,
    hit: 0.9,
    evade: 0,
    aggro: true,
    aggroWait: 0,
    living: true,
    XPFactor: 0,
    plasmoidFactor: .15,
    loot1: ['monster', 0, 0],
    loot2: false,
    ID: 0
  },
  {
    entry: [''],
    title: 'Shade',
    roomDesc: ".",
    roomDescDeath: ".",
    inspectDesc: ".",
    inspectDescDeath: ".",
    aggroDesc: false,
    deathDesc: "dies",
    atkVerb: "strikes",
    class: ['medium'],
    HPFactor: 4,
    dmgFactor: 3,
    atkSpd: 10,
    spreadFactor: 1,
    guard: true,
    guardWait: 4,
    guardCounter: 0,
    hit: 0.9,
    evade: 0,
    aggro: false,
    aggroWait: 0,
    living: true,
    XPFactor: 0,
    plasmoidFactor: .15,
    loot1: ['monster', 0, 0],
    loot2: false,
    ID: 0
  },
  {
    entry: [''],
    title: 'Spitter',
    roomDesc: "A vile <w>Spitter</w> sits in a pool of acid.",
    roomDescDeath: "A <w>Spitter</w> lies slain in its own acid.",
    inspectDesc: "A demonic creature that spits a vile, acidic ink. They can turn up in all sorts of unexpected places.",
    inspectDescDeath: "It's dead.",
    aggroDesc: false,
    deathDesc: "The Spitter bubbles over with purple mucus.",
    atkVerb: "spits",
    class: ['medium'],
    HPFactor: 2,
    dmgFactor: 6,
    atkSpd: 15,
    spreadFactor: 1,
    guard: true,
    guardWait: 4,
    guardCounter: 0,
    hit: 0.4,
    evade: 0,
    aggro: false,
    aggroWait: 0,
    living: true,
    XPFactor: 0,
    plasmoidFactor: .15,
    loot1: ['monster', 2, .7],
    loot2: ['mystical', 1, .3],
    ID: 14
  },
  {
    entry: [''],
    title: 'Vanta Phatom',
    roomDesc: ".",
    roomDescDeath: ".",
    inspectDesc: ".",
    inspectDescDeath: ".",
    aggroDesc: false,
    deathDesc: "dies",
    atkVerb: "strikes",
    class: ['medium'],
    HPFactor: 6,
    dmgFactor: 10,
    atkSpd: 10,
    spreadFactor: 1,
    guardWait: 0,
    guardCounter: 0,
    hit: 0.9,
    evade: 0,
    aggro: false,
    aggroWait: 0,
    living: true,
    XPFactor: 0,
    plasmoidFactor: .15,
    loot1: ['monster', 0, 0],
    loot2: false,
    ID: 0
  },
  {
    entry: [''],
    title: 'Warlock',
    roomDesc: ".",
    roomDescDeath: ".",
    inspectDesc: ".",
    inspectDescDeath: ".",
    aggroDesc: false,
    deathDesc: "dies",
    atkVerb: "strikes",
    class: ['medium'],
    HPFactor: 3,
    dmgFactor: 6,
    atkSpd: 10,
    spreadFactor: 1,
    guard: true,
    guardWait: 5,
    guardCounter: 0,
    hit: 0.9,
    evade: 0,
    aggro: false,
    aggroWait: 0,
    living: true,
    XPFactor: 0,
    plasmoidFactor: .15,
    loot1: ['monster', 0, 0],
    loot2: false,
    ID: 0
  },
  {
    entry: [''],
    title: 'Royal Warlock',
    roomDesc: ".",
    roomDescDeath: ".",
    inspectDesc: ".",
    inspectDescDeath: ".",
    aggroDesc: false,
    deathDesc: "dies",
    atkVerb: "strikes",
    class: ['large'],
    HPFactor: 6,
    dmgFactor: 8,
    atkSpd: 10,
    spreadFactor: 1,
    guard: true,
    guardWait: 3,
    guardCounter: 0,
    hit: 0.9,
    evade: 0,
    aggro: false,
    aggroWait: 0,
    living: true,
    XPFactor: 0,
    plasmoidFactor: .15,
    loot1: ['monster', 0, 0],
    loot2: false,
    ID: 0
  },

  /////////////////////////////////////////////
  /* BOSSES & MINIBOSSES */
  /////////////////////////////////////////////

  {
    entry: ['spitter', 'midnight', 'spit'],
    title: 'Midnight Spitter',
    roomDesc: "A vile Midnight <boss>Spitter</boss> sits in a pool of acid.",
    roomDescDeath: "The Midnight <boss>Spitter</boss> lies slain in its own acid.",
    inspectDesc: "A demonic creature that spits a vile, acidic ink. Guards incessantly.",
    inspectDescDeath: "It's very dead.",
    aggroDesc: false,
    deathDesc: "The massive Spitter bubbles over with purple mucus.",
    atkVerb: "spits",
    class: ['medium'],
    HPMin: 800,
    HPMax: 1000,
    HPFactor: 25,
    dmgFactor: 3,
    atkSpd: 10,
    spreadFactor: 1,
    guard: true,
    guardWait: 0,
    guardCounter: 0,
    hit: 0.65,
    evade: 0,
    aggro: false,
    aggroWait: 0,
    living: true,
    unique: true,
    XPFactor: 20,
    plasmoidFactor: 1,
    loot1: ['monster', 2, 1],
    loot2: ['mystical', 1, 1],
    ID: 201
  },
  {
    entry: ['harpy', 'harp'],
    title: 'Blood-Tinged Harpy',
    roomDesc: "A starved <boss>Harpy</boss> is perched on the outcropping, talons gripping the bare stone. Its leathery wings claw idly at the air.",
    roomDescDeath: "Only feathers remain of the Blood-Tinged <boss>Harpy</boss> that fell to its death.",
    inspectDesc: "It scans the countryside far below, lusting for whom it may consume. Its mangy feathers have seen many battles, and its talons are as quick as ever.",
    inspectDescDeath: "Pieces of its flesh are scattered from your battle, but the body is nowhere to be found.",
    aggroDesc: false,
    deathDesc: "Letting out a long cry, the Harpy flutters around madly. Its wings fail, and the cursed creature plummets down to the earth below.",
    atkVerb: "claws",
    class: ['small'],
    HPMin: 1600,
    HPMax: 2350,
    HPFactor: 27,
    dmgFactor: 3,
    atkSpd: 12,
    spreadFactor: 2,
    guard: false,
    guardWait: 0,
    guardCounter: 0,
    hit: 0.7,
    evade: 0.2,
    aggro: false,
    aggroWait: 0,
    skills: [
      {
        entry: ['predator'],
        title: 'Predator',
        interruptable: true,
        startup: 36, //how many ticks it takes to execute
        freq: 2, //how often it will roll for this skill (in turns)
        freqChance: .8, //how often it will actually use the skill on that turn
        numOfAtks: 1,
        dmgFactor: 4,
        hit: .9,
        ailment: {
          type: 'delay',
          hit: 1,
          duration: 15,
        },
        telegraph: "The <boss>Harpy</boss> lets out an ear-splitting scream and <sk>charges an attack</sk>!",
        hitLog: "The <boss>Harpy</boss> swoops down and <r>digs her talons into you</r>",
        missLog: "The <boss>Harpy</boss> swoops down with her talons, but <g>misses</g>!",
      }
    ],
    living: true,
    XPFactor: 35,
    plasmoidFactor: 1,
    loot1: ['monster', 1, 1],
    loot2: ['mystical', 2, 1],
    uniqueLoot: [
      {ID: 200, qty: 1},
      {ID: 201, qty: 1}
    ],
    ID: 202
  },
  {
    entry: ['golem', 'armed', 'one', 'arm', 'gol'],
    title: 'One-Armed Golem',
    roomDesc: "A <boss>One-Armed Golem</boss> is hunched over, feeding on a pile of precious stones.",
    roomDescDeath: "Only stone rubble is left from your fight with the <boss>One-Armed Golem</boss>.",
    inspectDesc: "The hulking Golem has scratches and chinks in his stony hide from years of combat.",
    inspectDescDeath: "Seems to have been held together by some feat of science - or magic?",
    deathDesc: "A sudden explosion sends rocky debris in all directions.",
    aggroDesc: false,
    atkVerb: 'smashes',
    class: ['medium'],
    HPMin: 1800,
    HPMax: 2600,
    HPFactor: 30,
    dmgFactor: 4,
    atkSpd: 15,
    spreadFactor: 2,
    guard: true,
    guardWait: 0,
    guardCounter: 0,
    hit: 0.7,
    evade: 0,
    defense: 0,
    aggro: false,
    aggroWait: 0,
    skills: [
      {
        entry: ['throw'],
        title: 'Throw',
        interruptable: true,
        startup: 18, //how many ticks it takes to execute
        freq: 1, //how often it will roll for this skill (in turns)
        freqChance: .6, //how often it will actually use the skill on that turn
        numOfAtks: 1,
        dmgFactor: 3,
        hit: .9,
        ailment: {
          type: 'delay',
          hit: 1,
          duration: 18,
        },
        telegraph: "<boss>One-Armed Golem</boss> rears back and <sk>prepares an attack</sk>!",
        hitLog: "<boss>One-Armed Golem</boss> grabs you by the neck and <r>throws you across the room</r>", // for XX damage
        missLog: "<boss>One-Armed Golem</boss> attempts to grapple you, but <g>misses</g>!",
      }
    ],
    living: true,
    XPFactor: 25,
    plasmoidFactor: 1,
    loot1: ['monster', 2, 1],
    loot2: ['mystical', 2, 1],
    uniqueLoot: [{ID: 326, qty: 3}], //lodestone
    ID: 203
  },
  {
    entry: [''],
    title: '',
    roomDesc: "<boss></boss>.",
    roomDescDeath: "<boss></boss>.",
    inspectDesc: ".",
    inspectDescDeath: ".",
    aggroDesc: false,
    deathDesc: ".",
    atkVerb: '',
    class: [''],
    HPMin: 0,
    HPMax: 0,
    HPFactor: 25,
    dmgFactor: 3,
    atkSpd: 10,
    spreadFactor: 2,
    guard: false,
    guardWait: 0,
    guardCounter: 0,
    hit: 0.7,
    evade: 0,
    defense: 0,
    aggro: false,
    aggroWait: 0,
    skills: [
      {
        entry: ['entry'],
        title: 'TITLE',
        interruptable: true,
        startup: 36, //how many ticks it takes to execute
        freq: 2, //how often it will roll for this skill (in turns)
        freqChance: .8, //how often it will actually use the skill on that turn
        numOfAtks: 1,
        dmgFactor: 4,
        hit: .9,
        telegraph: "<boss></boss> <sk>charges an attack</sk>!",
        hitLog: "<boss></boss> <r></r>", // for XX damage
        missLog: "<boss></boss> , but <g>misses</g>!",
      }
    ],
    living: true,
    XPFactor: 25,
    plasmoidFactor: 1,
    loot1: ['monster', 2, 1],
    loot2: ['mystical', 2, 1],
    uniqueLoot: [],
    ID: 200
  },
  {
    entry: [''],
    title: '',
    roomDesc: "<boss></boss>.",
    roomDescDeath: "<boss></boss>.",
    inspectDesc: ".",
    inspectDescDeath: ".",
    aggroDesc: false,
    deathDesc: ".",
    atkVerb: '',
    class: [''],
    HPMin: 0,
    HPMax: 0,
    HPFactor: 25,
    dmgFactor: 3,
    atkSpd: 10,
    spreadFactor: 2,
    guard: false,
    guardWait: 0,
    guardCounter: 0,
    hit: 0.7,
    evade: 0,
    defense: 0,
    aggro: false,
    aggroWait: 0,
    skills: [
      {
        entry: ['entry'],
        title: 'TITLE',
        interruptable: true,
        startup: 36, //how many ticks it takes to execute
        freq: 2, //how often it will roll for this skill (in turns)
        freqChance: .8, //how often it will actually use the skill on that turn
        numOfAtks: 1,
        dmgFactor: 4,
        hit: .9,
        telegraph: "<boss></boss> <sk>charges an attack</sk>!",
        hitLog: "<boss></boss> <r></r>", // for XX damage
        missLog: "<boss></boss> , but <g>misses</g>!",
      }
    ],
    living: true,
    XPFactor: 25,
    plasmoidFactor: 1,
    loot1: ['monster', 2, 1],
    loot2: ['mystical', 2, 1],
    uniqueLoot: [],
    ID: 200
  },
];
